#define PLOOPY_DRAGSCROLL_FIXED
#define PLOOPY_DRAGSCROLL_DPI 100
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT

#define PLOOPY_DPI_OPTIONS {1400, 1600, 1800}
#define PLOOPY_DPI_DEFAULT 1

#define OPT_SCALE -1
